version: '2'
services:
  odoo:
    image: odoo:9.0
    depends_on:
      - postgres
    links:
      - postgres:db
    ports:
      - "8069:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - odoo:/var/lib/odoo
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  odoo:
  pgdata: